name: 'Pull Request Semver tagger'

description: 'Tags a pull request with a semver version'
inputs:
  github-token:  # id of input
    description: 'The token to use to write tags'
    required: true
    default: undefined
  prefix:
    description: 'The prefix to use for the tag'
    required: false
    default: 'v'
  tag-prerelease:
    description: 'Should prerelease tags be added to the head branch of the PR?'
    required: false
    default: 'false'
  minor-release-label:
    description: 'The label to use for a minor release'
    required: false
    default: 'minor'
  major-release-label:
    description: 'The label to use for a major release'
    required: false
    default: 'major'
  prerelease-label:
    description: 'The label to use to trigger a prerelease'
    required: false
    default: 'prerelease'
  release-branches:
    description: 'The branches to release to, as a comma separated list of strings'
    required: false
    default: 'main'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'tag'
  color: 'green'
